application: rick-garlick-slack-interview
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:


- url: /$
  static_files: app/url_retriever/static/home.html
  upload: app/url_retriever/static/.*

- url: /lib/(.*)
  static_files: app/lib/\1
  upload: app/lib/.*

- url: /api/.*
  script: app.url_retriever.api.application

- url: /(.*)
  static_files: app/url_retriever/static/\1
  upload: app/url_retriever/static/.*



libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

