application: rick-garlick
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /url_retriever/$
  static_files: app/url_retriever/static/home.html
  upload: app/url_retriever/static/.*

- url: /url_retriever/api/.*
  script: app.url_retriever.api.application

- url: /url_retriever/(.*)
  static_files: app/url_retriever/static/\1
  upload: app/url_retriever/static/.*

- url: /lib/(.*)
  static_files: app/lib/\1
  upload: app/lib/.*

libraries:
- name: webapp2
  version: latest
